### ISSUE TITLE
LHC hydro from SMASH crashes

### ISSUE THREAD

**Issue by thegarzo** [smash-transport/smash-vhlle-hybrid#1]
Hydro crashes at LHC energies since the number of particles is Hardcoded to be NP=10000 in the vhlle icPartSmash.h source file. The solution is to increase it. However, since some people may not need this, and this increases the memory need, I suggest including a warning. Or maybe including a note in the README

**Comment by akschaefer** [comment]
As this is rather a problem of the hydro, I opened issue https://github.com/yukarpenko/vhlle/issues/7, to take care of it. Thus closing.
