### ISSUE TITLE
Extend hybrid approach to LHC energies

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/smash-vhlle-hybrid#24]
PbPb at 2760.0 GeV and 5020.0 GeV are to be included as targets. The parameter files have to be tuned and the performance of the different modules at these energies have to be tested.

**Comment by NGoetz** [comment]
@zpauliny 
I adapted the sampler to deal with higher multiplicities and performed tuning to ALICE data (see PR #25 ). The plots (at limited statistics) of the analysis targets show the following:
2.76 TeV: 
[dNdy.pdf](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674049/dNdy.pdf)
[pT.pdf](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674050/pT.pdf)
[meanpT.txt](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674177/meanpT.txt)
[midyY.txt](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674178/midyY.txt)
[int_vn.txt](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674186/int_vn.txt)
midrapidity yield:
5.02 TeV:
[dNdy.pdf](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674052/dNdy.pdf)
[pT.pdf](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674053/pT.pdf)
[midyY.txt](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674171/midyY.txt)
[meanpT.txt](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674172/meanpT.txt)
[int_vn.txt](https://github.com/smash-transport/smash-vhlle-hybrid/files/10674187/int_vn.txt)

**Comment by zpauliny** [comment]
Thanks, I think it looks reasonable and you can close the issue.
